// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0-devel
// 	protoc        v3.20.1--rc1
// source: webapi.proto

package webapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MenuRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleName string `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name"`
}

func (x *MenuRoleReq) Reset() {
	*x = MenuRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MenuRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuRoleReq) ProtoMessage() {}

func (x *MenuRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuRoleReq.ProtoReflect.Descriptor instead.
func (*MenuRoleReq) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{0}
}

func (x *MenuRoleReq) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type MenuRoleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg"`
}

func (x *MenuRoleReply) Reset() {
	*x = MenuRoleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MenuRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuRoleReply) ProtoMessage() {}

func (x *MenuRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuRoleReply.ProtoReflect.Descriptor instead.
func (*MenuRoleReply) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{1}
}

func (x *MenuRoleReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MenuRoleReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetMenuRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page    int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	PerPage int32 `protobuf:"varint,2,opt,name=perPage,proto3" json:"perPage"`
}

func (x *GetMenuRoleReq) Reset() {
	*x = GetMenuRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuRoleReq) ProtoMessage() {}

func (x *GetMenuRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuRoleReq.ProtoReflect.Descriptor instead.
func (*GetMenuRoleReq) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{2}
}

func (x *GetMenuRoleReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMenuRoleReq) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type GetMenuRoleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Msg    string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg"`
	Data   *GetMenuRoleReply_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data"`
}

func (x *GetMenuRoleReply) Reset() {
	*x = GetMenuRoleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuRoleReply) ProtoMessage() {}

func (x *GetMenuRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuRoleReply.ProtoReflect.Descriptor instead.
func (*GetMenuRoleReply) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{3}
}

func (x *GetMenuRoleReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetMenuRoleReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetMenuRoleReply) GetData() *GetMenuRoleReply_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetAmisSchemaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Router string `protobuf:"bytes,1,opt,name=router,proto3" json:"router"`
}

func (x *GetAmisSchemaReq) Reset() {
	*x = GetAmisSchemaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAmisSchemaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAmisSchemaReq) ProtoMessage() {}

func (x *GetAmisSchemaReq) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAmisSchemaReq.ProtoReflect.Descriptor instead.
func (*GetAmisSchemaReq) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{4}
}

func (x *GetAmisSchemaReq) GetRouter() string {
	if x != nil {
		return x.Router
	}
	return ""
}

type GetAmisSchemaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32                    `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Msg    string                   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg"`
	Data   *GetAmisSchemaReply_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data"`
}

func (x *GetAmisSchemaReply) Reset() {
	*x = GetAmisSchemaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAmisSchemaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAmisSchemaReply) ProtoMessage() {}

func (x *GetAmisSchemaReply) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAmisSchemaReply.ProtoReflect.Descriptor instead.
func (*GetAmisSchemaReply) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{5}
}

func (x *GetAmisSchemaReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetAmisSchemaReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetAmisSchemaReply) GetData() *GetAmisSchemaReply_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateAmisSchemaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Router string `protobuf:"bytes,1,opt,name=router,proto3" json:"router"`
	Schema string `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema"`
}

func (x *UpdateAmisSchemaReq) Reset() {
	*x = UpdateAmisSchemaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAmisSchemaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAmisSchemaReq) ProtoMessage() {}

func (x *UpdateAmisSchemaReq) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAmisSchemaReq.ProtoReflect.Descriptor instead.
func (*UpdateAmisSchemaReq) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAmisSchemaReq) GetRouter() string {
	if x != nil {
		return x.Router
	}
	return ""
}

func (x *UpdateAmisSchemaReq) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

type UpdateAmisSchemaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg"`
}

func (x *UpdateAmisSchemaReply) Reset() {
	*x = UpdateAmisSchemaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAmisSchemaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAmisSchemaReply) ProtoMessage() {}

func (x *UpdateAmisSchemaReply) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAmisSchemaReply.ProtoReflect.Descriptor instead.
func (*UpdateAmisSchemaReply) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAmisSchemaReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateAmisSchemaReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type AddMenuReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path       string `protobuf:"bytes,1,opt,name=path,proto3" json:"path"`
	Icon       string `protobuf:"bytes,2,opt,name=icon,proto3" json:"icon"`
	Roles      string `protobuf:"bytes,3,opt,name=roles,proto3" json:"roles"`
	Layout     int32  `protobuf:"varint,4,opt,name=layout,proto3" json:"layout"`
	HideInMenu int32  `protobuf:"varint,5,opt,name=hideInMenu,proto3" json:"hideInMenu"`
	ParentId   int64  `protobuf:"varint,8,opt,name=parent_id,json=parentId,proto3" json:"parent_id"`
	Name       string `protobuf:"bytes,6,opt,name=name,proto3" json:"name"`
}

func (x *AddMenuReq) Reset() {
	*x = AddMenuReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMenuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMenuReq) ProtoMessage() {}

func (x *AddMenuReq) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMenuReq.ProtoReflect.Descriptor instead.
func (*AddMenuReq) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{8}
}

func (x *AddMenuReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AddMenuReq) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *AddMenuReq) GetRoles() string {
	if x != nil {
		return x.Roles
	}
	return ""
}

func (x *AddMenuReq) GetLayout() int32 {
	if x != nil {
		return x.Layout
	}
	return 0
}

func (x *AddMenuReq) GetHideInMenu() int32 {
	if x != nil {
		return x.HideInMenu
	}
	return 0
}

func (x *AddMenuReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *AddMenuReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AddMenuReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg"`
}

func (x *AddMenuReply) Reset() {
	*x = AddMenuReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMenuReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMenuReply) ProtoMessage() {}

func (x *AddMenuReply) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMenuReply.ProtoReflect.Descriptor instead.
func (*AddMenuReply) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{9}
}

func (x *AddMenuReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddMenuReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetMenuReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,3,opt,name=id,proto3" json:"id"`
	ParentId int64  `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id"`
	Roles    string `protobuf:"bytes,8,opt,name=roles,proto3" json:"roles"`
	Status   int32  `protobuf:"varint,9,opt,name=status,proto3" json:"status"`
}

func (x *GetMenuReq) Reset() {
	*x = GetMenuReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuReq) ProtoMessage() {}

func (x *GetMenuReq) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuReq.ProtoReflect.Descriptor instead.
func (*GetMenuReq) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{10}
}

func (x *GetMenuReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetMenuReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *GetMenuReq) GetRoles() string {
	if x != nil {
		return x.Roles
	}
	return ""
}

func (x *GetMenuReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetMenuReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32              `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Msg    string             `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg"`
	Data   *GetMenuReply_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data"`
}

func (x *GetMenuReply) Reset() {
	*x = GetMenuReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuReply) ProtoMessage() {}

func (x *GetMenuReply) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuReply.ProtoReflect.Descriptor instead.
func (*GetMenuReply) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{11}
}

func (x *GetMenuReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetMenuReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetMenuReply) GetData() *GetMenuReply_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type BulkDelMenuReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids string `protobuf:"bytes,1,opt,name=ids,proto3" json:"ids"`
}

func (x *BulkDelMenuReq) Reset() {
	*x = BulkDelMenuReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BulkDelMenuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkDelMenuReq) ProtoMessage() {}

func (x *BulkDelMenuReq) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkDelMenuReq.ProtoReflect.Descriptor instead.
func (*BulkDelMenuReq) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{12}
}

func (x *BulkDelMenuReq) GetIds() string {
	if x != nil {
		return x.Ids
	}
	return ""
}

type DelMenuReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
}

func (x *DelMenuReq) Reset() {
	*x = DelMenuReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelMenuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelMenuReq) ProtoMessage() {}

func (x *DelMenuReq) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelMenuReq.ProtoReflect.Descriptor instead.
func (*DelMenuReq) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{13}
}

func (x *DelMenuReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DelMenuReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg"`
}

func (x *DelMenuReply) Reset() {
	*x = DelMenuReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelMenuReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelMenuReply) ProtoMessage() {}

func (x *DelMenuReply) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelMenuReply.ProtoReflect.Descriptor instead.
func (*DelMenuReply) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{14}
}

func (x *DelMenuReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DelMenuReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdateMenuReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Path       string `protobuf:"bytes,2,opt,name=path,proto3" json:"path"`
	Icon       string `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon"`
	Roles      string `protobuf:"bytes,4,opt,name=roles,proto3" json:"roles"`
	Layout     int32  `protobuf:"varint,5,opt,name=layout,proto3" json:"layout"`
	HideInMenu int32  `protobuf:"varint,6,opt,name=hide_in_menu,json=hideInMenu,proto3" json:"hide_in_menu"`
	MenuName   string `protobuf:"bytes,7,opt,name=menu_name,json=menuName,proto3" json:"menu_name"`
	ParentId   int64  `protobuf:"varint,8,opt,name=parent_id,json=parentId,proto3" json:"parent_id"`
	Status     int32  `protobuf:"varint,9,opt,name=status,proto3" json:"status"`
}

func (x *UpdateMenuReq) Reset() {
	*x = UpdateMenuReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMenuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuReq) ProtoMessage() {}

func (x *UpdateMenuReq) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuReq.ProtoReflect.Descriptor instead.
func (*UpdateMenuReq) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateMenuReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMenuReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UpdateMenuReq) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *UpdateMenuReq) GetRoles() string {
	if x != nil {
		return x.Roles
	}
	return ""
}

func (x *UpdateMenuReq) GetLayout() int32 {
	if x != nil {
		return x.Layout
	}
	return 0
}

func (x *UpdateMenuReq) GetHideInMenu() int32 {
	if x != nil {
		return x.HideInMenu
	}
	return 0
}

func (x *UpdateMenuReq) GetMenuName() string {
	if x != nil {
		return x.MenuName
	}
	return ""
}

func (x *UpdateMenuReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *UpdateMenuReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateMenuReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg"`
}

func (x *UpdateMenuReply) Reset() {
	*x = UpdateMenuReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMenuReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuReply) ProtoMessage() {}

func (x *UpdateMenuReply) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuReply.ProtoReflect.Descriptor instead.
func (*UpdateMenuReply) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateMenuReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateMenuReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type OrderMenuReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OrderMenuReq) Reset() {
	*x = OrderMenuReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderMenuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderMenuReq) ProtoMessage() {}

func (x *OrderMenuReq) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderMenuReq.ProtoReflect.Descriptor instead.
func (*OrderMenuReq) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{17}
}

type OrderMenuReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg"`
}

func (x *OrderMenuReply) Reset() {
	*x = OrderMenuReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderMenuReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderMenuReply) ProtoMessage() {}

func (x *OrderMenuReply) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderMenuReply.ProtoReflect.Descriptor instead.
func (*OrderMenuReply) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{18}
}

func (x *OrderMenuReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderMenuReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetMenuTreeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles string `protobuf:"bytes,4,opt,name=roles,proto3" json:"roles"`
}

func (x *GetMenuTreeReq) Reset() {
	*x = GetMenuTreeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuTreeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuTreeReq) ProtoMessage() {}

func (x *GetMenuTreeReq) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuTreeReq.ProtoReflect.Descriptor instead.
func (*GetMenuTreeReq) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{19}
}

func (x *GetMenuTreeReq) GetRoles() string {
	if x != nil {
		return x.Roles
	}
	return ""
}

type GetMenuTreeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*GetMenuTreeReply_Data `protobuf:"bytes,4,rep,name=data,proto3" json:"data"`
}

func (x *GetMenuTreeReply) Reset() {
	*x = GetMenuTreeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuTreeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuTreeReply) ProtoMessage() {}

func (x *GetMenuTreeReply) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuTreeReply.ProtoReflect.Descriptor instead.
func (*GetMenuTreeReply) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{20}
}

func (x *GetMenuTreeReply) GetData() []*GetMenuTreeReply_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetMenuRoleReply_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*GetMenuRoleReply_Data_List `protobuf:"bytes,1,rep,name=items,proto3" json:"items"`
	Total int32                         `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
}

func (x *GetMenuRoleReply_Data) Reset() {
	*x = GetMenuRoleReply_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuRoleReply_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuRoleReply_Data) ProtoMessage() {}

func (x *GetMenuRoleReply_Data) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuRoleReply_Data.ProtoReflect.Descriptor instead.
func (*GetMenuRoleReply_Data) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetMenuRoleReply_Data) GetItems() []*GetMenuRoleReply_Data_List {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetMenuRoleReply_Data) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetMenuRoleReply_Data_List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID"`
	RoleName string `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name"`
}

func (x *GetMenuRoleReply_Data_List) Reset() {
	*x = GetMenuRoleReply_Data_List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuRoleReply_Data_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuRoleReply_Data_List) ProtoMessage() {}

func (x *GetMenuRoleReply_Data_List) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuRoleReply_Data_List.ProtoReflect.Descriptor instead.
func (*GetMenuRoleReply_Data_List) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *GetMenuRoleReply_Data_List) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GetMenuRoleReply_Data_List) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type GetAmisSchemaReply_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Schema string `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema"`
}

func (x *GetAmisSchemaReply_Data) Reset() {
	*x = GetAmisSchemaReply_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAmisSchemaReply_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAmisSchemaReply_Data) ProtoMessage() {}

func (x *GetAmisSchemaReply_Data) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAmisSchemaReply_Data.ProtoReflect.Descriptor instead.
func (*GetAmisSchemaReply_Data) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetAmisSchemaReply_Data) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

type GetMenuReply_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*GetMenuReply_Data_List `protobuf:"bytes,1,rep,name=items,proto3" json:"items"`
	Total int32                     `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
}

func (x *GetMenuReply_Data) Reset() {
	*x = GetMenuReply_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuReply_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuReply_Data) ProtoMessage() {}

func (x *GetMenuReply_Data) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuReply_Data.ProtoReflect.Descriptor instead.
func (*GetMenuReply_Data) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{11, 0}
}

func (x *GetMenuReply_Data) GetItems() []*GetMenuReply_Data_List {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetMenuReply_Data) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetMenuReply_Data_List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32                     `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Path       string                    `protobuf:"bytes,2,opt,name=path,proto3" json:"path"`
	Icon       string                    `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon"`
	Roles      string                    `protobuf:"bytes,4,opt,name=roles,proto3" json:"roles"`
	ParentId   int64                     `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id"`
	HideInMenu int32                     `protobuf:"varint,6,opt,name=hide_in_menu,json=hideInMenu,proto3" json:"hide_in_menu"`
	MenuName   string                    `protobuf:"bytes,7,opt,name=menu_name,json=menuName,proto3" json:"menu_name"`
	Layout     int32                     `protobuf:"varint,8,opt,name=layout,proto3" json:"layout"`
	Status     int32                     `protobuf:"varint,9,opt,name=status,proto3" json:"status"`
	Children   []*GetMenuReply_Data_List `protobuf:"bytes,11,rep,name=children,proto3" json:"children"`
}

func (x *GetMenuReply_Data_List) Reset() {
	*x = GetMenuReply_Data_List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuReply_Data_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuReply_Data_List) ProtoMessage() {}

func (x *GetMenuReply_Data_List) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuReply_Data_List.ProtoReflect.Descriptor instead.
func (*GetMenuReply_Data_List) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{11, 0, 0}
}

func (x *GetMenuReply_Data_List) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetMenuReply_Data_List) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetMenuReply_Data_List) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *GetMenuReply_Data_List) GetRoles() string {
	if x != nil {
		return x.Roles
	}
	return ""
}

func (x *GetMenuReply_Data_List) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *GetMenuReply_Data_List) GetHideInMenu() int32 {
	if x != nil {
		return x.HideInMenu
	}
	return 0
}

func (x *GetMenuReply_Data_List) GetMenuName() string {
	if x != nil {
		return x.MenuName
	}
	return ""
}

func (x *GetMenuReply_Data_List) GetLayout() int32 {
	if x != nil {
		return x.Layout
	}
	return 0
}

func (x *GetMenuReply_Data_List) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetMenuReply_Data_List) GetChildren() []*GetMenuReply_Data_List {
	if x != nil {
		return x.Children
	}
	return nil
}

type GetMenuTreeReply_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path       string                   `protobuf:"bytes,1,opt,name=path,proto3" json:"path"`
	Layout     bool                     `protobuf:"varint,2,opt,name=layout,proto3" json:"layout"`
	HideInMenu bool                     `protobuf:"varint,3,opt,name=hideInMenu,proto3" json:"hideInMenu"`
	Status     bool                     `protobuf:"varint,12,opt,name=status,proto3" json:"status"`
	Icon       string                   `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon"`
	Name       string                   `protobuf:"bytes,5,opt,name=name,proto3" json:"name"`
	Roles      []string                 `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles"`
	Access     string                   `protobuf:"bytes,7,opt,name=access,proto3" json:"access"`
	Component  string                   `protobuf:"bytes,8,opt,name=component,proto3" json:"component"`
	Wrappers   []string                 `protobuf:"bytes,9,rep,name=wrappers,proto3" json:"wrappers"`
	Redirect   string                   `protobuf:"bytes,10,opt,name=redirect,proto3" json:"redirect"`
	Routes     []*GetMenuTreeReply_Data `protobuf:"bytes,11,rep,name=routes,proto3" json:"routes"`
}

func (x *GetMenuTreeReply_Data) Reset() {
	*x = GetMenuTreeReply_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webapi_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuTreeReply_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuTreeReply_Data) ProtoMessage() {}

func (x *GetMenuTreeReply_Data) ProtoReflect() protoreflect.Message {
	mi := &file_webapi_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuTreeReply_Data.ProtoReflect.Descriptor instead.
func (*GetMenuTreeReply_Data) Descriptor() ([]byte, []int) {
	return file_webapi_proto_rawDescGZIP(), []int{20, 0}
}

func (x *GetMenuTreeReply_Data) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetMenuTreeReply_Data) GetLayout() bool {
	if x != nil {
		return x.Layout
	}
	return false
}

func (x *GetMenuTreeReply_Data) GetHideInMenu() bool {
	if x != nil {
		return x.HideInMenu
	}
	return false
}

func (x *GetMenuTreeReply_Data) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *GetMenuTreeReply_Data) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *GetMenuTreeReply_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetMenuTreeReply_Data) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *GetMenuTreeReply_Data) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *GetMenuTreeReply_Data) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *GetMenuTreeReply_Data) GetWrappers() []string {
	if x != nil {
		return x.Wrappers
	}
	return nil
}

func (x *GetMenuTreeReply_Data) GetRedirect() string {
	if x != nil {
		return x.Redirect
	}
	return ""
}

func (x *GetMenuTreeReply_Data) GetRoutes() []*GetMenuTreeReply_Data {
	if x != nil {
		return x.Routes
	}
	return nil
}

var File_webapi_proto protoreflect.FileDescriptor

var file_webapi_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x77, 0x65, 0x62, 0x61, 0x70, 0x69, 0x22, 0x2a, 0x0a, 0x0b, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x6f,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x39, 0x0a, 0x0d, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x3e, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x22, 0xfd, 0x01,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x31, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x77, 0x65, 0x62,
	0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x6f, 0x6c, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a,
	0x8b, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x38, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69,
	0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x1a, 0x33, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2a, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x69, 0x73, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x22, 0x93, 0x01, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x41, 0x6d, 0x69, 0x73, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x33, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x77, 0x65, 0x62, 0x61, 0x70,
	0x69, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x69, 0x73, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a,
	0x1e, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x22,
	0x45, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6d, 0x69, 0x73, 0x53, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x22, 0x41, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x41, 0x6d, 0x69, 0x73, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0xb3, 0x01, 0x0a, 0x0a, 0x41, 0x64,
	0x64, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04,
	0x69, 0x63, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x68, 0x69, 0x64, 0x65, 0x49, 0x6e, 0x4d, 0x65, 0x6e, 0x75, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x68, 0x69, 0x64, 0x65, 0x49, 0x6e, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x38, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x67, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0xdb, 0x03, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2d, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x77, 0x65,
	0x62, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0xf1, 0x02, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x34, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x1a, 0x9c, 0x02, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12,
	0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x68, 0x69, 0x64, 0x65, 0x5f, 0x69, 0x6e,
	0x5f, 0x6d, 0x65, 0x6e, 0x75, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x68, 0x69, 0x64,
	0x65, 0x49, 0x6e, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x6e, 0x75, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x6e, 0x75,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x3a, 0x0a, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e,
	0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69, 0x2e,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e,
	0x22, 0x22, 0x0a, 0x0e, 0x42, 0x75, 0x6c, 0x6b, 0x44, 0x65, 0x6c, 0x4d, 0x65, 0x6e, 0x75, 0x52,
	0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x69, 0x64, 0x73, 0x22, 0x1c, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x4d, 0x65, 0x6e, 0x75, 0x52,
	0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x38, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0xe9, 0x01, 0x0a,
	0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x61,
	0x79, 0x6f, 0x75, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x68, 0x69, 0x64, 0x65, 0x5f, 0x69, 0x6e, 0x5f,
	0x6d, 0x65, 0x6e, 0x75, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x68, 0x69, 0x64, 0x65,
	0x49, 0x6e, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x6e, 0x75, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x6e, 0x75, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3b, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x0e, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x65,
	0x6e, 0x75, 0x52, 0x65, 0x71, 0x22, 0x3a, 0x0a, 0x0e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x65,
	0x6e, 0x75, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x22, 0x26, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x54, 0x72, 0x65, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x95, 0x03, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x6e, 0x75, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x31,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x77,
	0x65, 0x62, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x54, 0x72, 0x65,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x1a, 0xcd, 0x02, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x16,
	0x0a, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x69, 0x64, 0x65, 0x49, 0x6e,
	0x4d, 0x65, 0x6e, 0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x68, 0x69, 0x64, 0x65,
	0x49, 0x6e, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65,
	0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x18, 0x09,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x12, 0x35, 0x0a, 0x06, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x77, 0x65, 0x62,
	0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x54, 0x72, 0x65, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x73, 0x32, 0xec, 0x05, 0x0a, 0x06, 0x57, 0x65, 0x62, 0x61, 0x70, 0x69, 0x12, 0x45, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x41, 0x6d, 0x69, 0x73, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x18, 0x2e,
	0x77, 0x65, 0x62, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x69, 0x73, 0x53, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x69, 0x73, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x4e, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6d, 0x69,
	0x73, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x1b, 0x2e, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6d, 0x69, 0x73, 0x53, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x41, 0x6d, 0x69, 0x73, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x39, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x6f,
	0x6c, 0x65, 0x12, 0x13, 0x2e, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x6e, 0x75,
	0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69,
	0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x39,
	0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x13, 0x2e,
	0x77, 0x65, 0x62, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x6f, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x15, 0x2e, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x6e, 0x75,
	0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3f, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x6e, 0x75, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x16, 0x2e, 0x77, 0x65, 0x62, 0x61, 0x70,
	0x69, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x18, 0x2e, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e,
	0x75, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x33, 0x0a, 0x07, 0x41, 0x64,
	0x64, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x12, 0x2e, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69, 0x2e, 0x41,
	0x64, 0x64, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x77, 0x65, 0x62, 0x61,
	0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x33, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x12, 0x2e, 0x77, 0x65, 0x62,
	0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x71, 0x1a, 0x14,
	0x2e, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x33, 0x0a, 0x07, 0x44, 0x65, 0x6c, 0x4d, 0x65, 0x6e, 0x75, 0x12,
	0x12, 0x2e, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c, 0x4d, 0x65, 0x6e, 0x75,
	0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c,
	0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3c, 0x0a, 0x0a, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x15, 0x2e, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x71, 0x1a, 0x17,
	0x2e, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65,
	0x6e, 0x75, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3b, 0x0a, 0x0b, 0x42, 0x75, 0x6c, 0x6b, 0x44,
	0x65, 0x6c, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x16, 0x2e, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69, 0x2e,
	0x42, 0x75, 0x6c, 0x6b, 0x44, 0x65, 0x6c, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x71, 0x1a, 0x14,
	0x2e, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c, 0x4d, 0x65, 0x6e, 0x75, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x39, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x65, 0x6e,
	0x75, 0x12, 0x14, 0x2e, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69,
	0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x3f, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x54, 0x72, 0x65, 0x65, 0x12, 0x16,
	0x2e, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x54,
	0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69, 0x2e,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x77, 0x65, 0x62, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_webapi_proto_rawDescOnce sync.Once
	file_webapi_proto_rawDescData = file_webapi_proto_rawDesc
)

func file_webapi_proto_rawDescGZIP() []byte {
	file_webapi_proto_rawDescOnce.Do(func() {
		file_webapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_webapi_proto_rawDescData)
	})
	return file_webapi_proto_rawDescData
}

var file_webapi_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_webapi_proto_goTypes = []interface{}{
	(*MenuRoleReq)(nil),                // 0: webapi.MenuRoleReq
	(*MenuRoleReply)(nil),              // 1: webapi.MenuRoleReply
	(*GetMenuRoleReq)(nil),             // 2: webapi.GetMenuRoleReq
	(*GetMenuRoleReply)(nil),           // 3: webapi.GetMenuRoleReply
	(*GetAmisSchemaReq)(nil),           // 4: webapi.GetAmisSchemaReq
	(*GetAmisSchemaReply)(nil),         // 5: webapi.GetAmisSchemaReply
	(*UpdateAmisSchemaReq)(nil),        // 6: webapi.UpdateAmisSchemaReq
	(*UpdateAmisSchemaReply)(nil),      // 7: webapi.UpdateAmisSchemaReply
	(*AddMenuReq)(nil),                 // 8: webapi.AddMenuReq
	(*AddMenuReply)(nil),               // 9: webapi.AddMenuReply
	(*GetMenuReq)(nil),                 // 10: webapi.GetMenuReq
	(*GetMenuReply)(nil),               // 11: webapi.GetMenuReply
	(*BulkDelMenuReq)(nil),             // 12: webapi.BulkDelMenuReq
	(*DelMenuReq)(nil),                 // 13: webapi.DelMenuReq
	(*DelMenuReply)(nil),               // 14: webapi.DelMenuReply
	(*UpdateMenuReq)(nil),              // 15: webapi.UpdateMenuReq
	(*UpdateMenuReply)(nil),            // 16: webapi.UpdateMenuReply
	(*OrderMenuReq)(nil),               // 17: webapi.OrderMenuReq
	(*OrderMenuReply)(nil),             // 18: webapi.OrderMenuReply
	(*GetMenuTreeReq)(nil),             // 19: webapi.GetMenuTreeReq
	(*GetMenuTreeReply)(nil),           // 20: webapi.GetMenuTreeReply
	(*GetMenuRoleReply_Data)(nil),      // 21: webapi.GetMenuRoleReply.Data
	(*GetMenuRoleReply_Data_List)(nil), // 22: webapi.GetMenuRoleReply.Data.List
	(*GetAmisSchemaReply_Data)(nil),    // 23: webapi.GetAmisSchemaReply.Data
	(*GetMenuReply_Data)(nil),          // 24: webapi.GetMenuReply.Data
	(*GetMenuReply_Data_List)(nil),     // 25: webapi.GetMenuReply.Data.List
	(*GetMenuTreeReply_Data)(nil),      // 26: webapi.GetMenuTreeReply.Data
}
var file_webapi_proto_depIdxs = []int32{
	21, // 0: webapi.GetMenuRoleReply.data:type_name -> webapi.GetMenuRoleReply.Data
	23, // 1: webapi.GetAmisSchemaReply.data:type_name -> webapi.GetAmisSchemaReply.Data
	24, // 2: webapi.GetMenuReply.data:type_name -> webapi.GetMenuReply.Data
	26, // 3: webapi.GetMenuTreeReply.data:type_name -> webapi.GetMenuTreeReply.Data
	22, // 4: webapi.GetMenuRoleReply.Data.items:type_name -> webapi.GetMenuRoleReply.Data.List
	25, // 5: webapi.GetMenuReply.Data.items:type_name -> webapi.GetMenuReply.Data.List
	25, // 6: webapi.GetMenuReply.Data.List.children:type_name -> webapi.GetMenuReply.Data.List
	26, // 7: webapi.GetMenuTreeReply.Data.routes:type_name -> webapi.GetMenuTreeReply.Data
	4,  // 8: webapi.Webapi.GetAmisSchema:input_type -> webapi.GetAmisSchemaReq
	6,  // 9: webapi.Webapi.UpdateAmisSchema:input_type -> webapi.UpdateAmisSchemaReq
	0,  // 10: webapi.Webapi.AddMenuRole:input_type -> webapi.MenuRoleReq
	0,  // 11: webapi.Webapi.DelMenuRole:input_type -> webapi.MenuRoleReq
	2,  // 12: webapi.Webapi.GetMenuRole:input_type -> webapi.GetMenuRoleReq
	8,  // 13: webapi.Webapi.AddMenu:input_type -> webapi.AddMenuReq
	10, // 14: webapi.Webapi.GetMenu:input_type -> webapi.GetMenuReq
	13, // 15: webapi.Webapi.DelMenu:input_type -> webapi.DelMenuReq
	15, // 16: webapi.Webapi.UpdateMenu:input_type -> webapi.UpdateMenuReq
	12, // 17: webapi.Webapi.BulkDelMenu:input_type -> webapi.BulkDelMenuReq
	17, // 18: webapi.Webapi.OrderMenu:input_type -> webapi.OrderMenuReq
	19, // 19: webapi.Webapi.GetMenuTree:input_type -> webapi.GetMenuTreeReq
	5,  // 20: webapi.Webapi.GetAmisSchema:output_type -> webapi.GetAmisSchemaReply
	7,  // 21: webapi.Webapi.UpdateAmisSchema:output_type -> webapi.UpdateAmisSchemaReply
	1,  // 22: webapi.Webapi.AddMenuRole:output_type -> webapi.MenuRoleReply
	1,  // 23: webapi.Webapi.DelMenuRole:output_type -> webapi.MenuRoleReply
	3,  // 24: webapi.Webapi.GetMenuRole:output_type -> webapi.GetMenuRoleReply
	9,  // 25: webapi.Webapi.AddMenu:output_type -> webapi.AddMenuReply
	11, // 26: webapi.Webapi.GetMenu:output_type -> webapi.GetMenuReply
	14, // 27: webapi.Webapi.DelMenu:output_type -> webapi.DelMenuReply
	16, // 28: webapi.Webapi.UpdateMenu:output_type -> webapi.UpdateMenuReply
	14, // 29: webapi.Webapi.BulkDelMenu:output_type -> webapi.DelMenuReply
	18, // 30: webapi.Webapi.OrderMenu:output_type -> webapi.OrderMenuReply
	20, // 31: webapi.Webapi.GetMenuTree:output_type -> webapi.GetMenuTreeReply
	20, // [20:32] is the sub-list for method output_type
	8,  // [8:20] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_webapi_proto_init() }
func file_webapi_proto_init() {
	if File_webapi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_webapi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MenuRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MenuRoleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenuRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenuRoleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAmisSchemaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAmisSchemaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAmisSchemaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAmisSchemaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMenuReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMenuReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenuReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenuReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BulkDelMenuReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelMenuReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelMenuReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMenuReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMenuReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderMenuReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderMenuReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenuTreeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenuTreeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenuRoleReply_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenuRoleReply_Data_List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAmisSchemaReply_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenuReply_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenuReply_Data_List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webapi_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenuTreeReply_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_webapi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_webapi_proto_goTypes,
		DependencyIndexes: file_webapi_proto_depIdxs,
		MessageInfos:      file_webapi_proto_msgTypes,
	}.Build()
	File_webapi_proto = out.File
	file_webapi_proto_rawDesc = nil
	file_webapi_proto_goTypes = nil
	file_webapi_proto_depIdxs = nil
}
