// Code generated by entc, DO NOT EDIT.

package menu

import (
	"time"
)

const (
	// Label holds the string label denoting the menu type in the database.
	Label = "menu"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMenuName holds the string denoting the menu_name field in the database.
	FieldMenuName = "menu_name"
	// FieldParentID holds the string denoting the parent_id field in the database.
	FieldParentID = "parent_id"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldIcon holds the string denoting the icon field in the database.
	FieldIcon = "icon"
	// FieldRoles holds the string denoting the roles field in the database.
	FieldRoles = "roles"
	// FieldLayout holds the string denoting the layout field in the database.
	FieldLayout = "layout"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldHideInMenu holds the string denoting the hide_in_menu field in the database.
	FieldHideInMenu = "hide_in_menu"
	// FieldSort holds the string denoting the sort field in the database.
	FieldSort = "sort"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the menu in the database.
	Table = "menus"
)

// Columns holds all SQL columns for menu fields.
var Columns = []string{
	FieldID,
	FieldMenuName,
	FieldParentID,
	FieldPath,
	FieldIcon,
	FieldRoles,
	FieldLayout,
	FieldStatus,
	FieldHideInMenu,
	FieldSort,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultParentID holds the default value on creation for the "parent_id" field.
	DefaultParentID int64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus bool
	// DefaultSort holds the default value on creation for the "sort" field.
	DefaultSort int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
