// Code generated by entc, DO NOT EDIT.

package amisschema

import (
	"time"
)

const (
	// Label holds the string label denoting the amisschema type in the database.
	Label = "amis_schema"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRouter holds the string denoting the router field in the database.
	FieldRouter = "router"
	// FieldSchema holds the string denoting the schema field in the database.
	FieldSchema = "schema"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the amisschema in the database.
	Table = "amis_schemas"
)

// Columns holds all SQL columns for amisschema fields.
var Columns = []string{
	FieldID,
	FieldRouter,
	FieldSchema,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
