// Code generated by entc, DO NOT EDIT.

package ent

import (
	"antd-pro-amis-server/rpc/ent/menurole"
	"antd-pro-amis-server/rpc/ent/predicate"
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MenuRoleDelete is the builder for deleting a MenuRole entity.
type MenuRoleDelete struct {
	config
	hooks    []Hook
	mutation *MenuRoleMutation
}

// Where appends a list predicates to the MenuRoleDelete builder.
func (mrd *MenuRoleDelete) Where(ps ...predicate.MenuRole) *MenuRoleDelete {
	mrd.mutation.Where(ps...)
	return mrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mrd *MenuRoleDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mrd.hooks) == 0 {
		affected, err = mrd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MenuRoleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mrd.mutation = mutation
			affected, err = mrd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mrd.hooks) - 1; i >= 0; i-- {
			if mrd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mrd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mrd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (mrd *MenuRoleDelete) ExecX(ctx context.Context) int {
	n, err := mrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mrd *MenuRoleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: menurole.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: menurole.FieldID,
			},
		},
	}
	if ps := mrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, mrd.driver, _spec)
}

// MenuRoleDeleteOne is the builder for deleting a single MenuRole entity.
type MenuRoleDeleteOne struct {
	mrd *MenuRoleDelete
}

// Exec executes the deletion query.
func (mrdo *MenuRoleDeleteOne) Exec(ctx context.Context) error {
	n, err := mrdo.mrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{menurole.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mrdo *MenuRoleDeleteOne) ExecX(ctx context.Context) {
	mrdo.mrd.ExecX(ctx)
}
