// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AmisSchemasColumns holds the columns for the "amis_schemas" table.
	AmisSchemasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "router", Type: field.TypeString},
		{Name: "schema", Type: field.TypeString, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AmisSchemasTable holds the schema information for the "amis_schemas" table.
	AmisSchemasTable = &schema.Table{
		Name:       "amis_schemas",
		Columns:    AmisSchemasColumns,
		PrimaryKey: []*schema.Column{AmisSchemasColumns[0]},
	}
	// MenusColumns holds the columns for the "menus" table.
	MenusColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "menu_name", Type: field.TypeString},
		{Name: "parent_id", Type: field.TypeInt64, Default: 0},
		{Name: "path", Type: field.TypeString},
		{Name: "icon", Type: field.TypeString},
		{Name: "roles", Type: field.TypeJSON},
		{Name: "layout", Type: field.TypeBool},
		{Name: "status", Type: field.TypeBool, Default: true},
		{Name: "hide_in_menu", Type: field.TypeBool},
		{Name: "sort", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// MenusTable holds the schema information for the "menus" table.
	MenusTable = &schema.Table{
		Name:       "menus",
		Columns:    MenusColumns,
		PrimaryKey: []*schema.Column{MenusColumns[0]},
	}
	// MenuRolesColumns holds the columns for the "menu_roles" table.
	MenuRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "role_name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// MenuRolesTable holds the schema information for the "menu_roles" table.
	MenuRolesTable = &schema.Table{
		Name:       "menu_roles",
		Columns:    MenuRolesColumns,
		PrimaryKey: []*schema.Column{MenuRolesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AmisSchemasTable,
		MenusTable,
		MenuRolesTable,
	}
)

func init() {
}
