// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AmisSchema is the predicate function for amisschema builders.
type AmisSchema func(*sql.Selector)

// Menu is the predicate function for menu builders.
type Menu func(*sql.Selector)

// MenuRole is the predicate function for menurole builders.
type MenuRole func(*sql.Selector)
