// Code generated by goctl. DO NOT EDIT.
package types

type AddMenuRolsRequest struct {
	RoleName string `json:"role_name"`
}

type DelMenuRolsRequest struct {
	RoleName string `json:"role_name"`
}

type GetMenuRolsRequest struct {
	Page    int `form:"page"`
	PerPage int `form:"perPage"`
}

type GetAmisSchemaRequest struct {
	Router string `form:"router"`
}

type UpdateAmisSchemaRequest struct {
	Router string `json:"router"`
	Schema string `json:"schema"`
}

type AddMenuRequest struct {
	Name       string `json:"menu_name"`
	Path       string `json:"path"`
	Icon       string `json:"icon"`
	Roles      string `json:"roles"`
	Layout     int32  `json:"layout"`
	ParentId   int64  `json:"parent_id"`
	HideInMenu int32  `json:"hide_in_menu"`
}

type GetMenuRequest struct {
	ParentId *int64 `form:"parent_id,optional"`
	Id       *int64 `form:"id,optional"`
	Status   *int32 `form:"status,optional"`
	Roles    string `form:"roles,optional"`
}

type DelMenuRequest struct {
	Id int64 `json:"id"`
}

type UpdateMenuRequest struct {
	Id         int64  `json:"id"`
	MenuName   string `json:"menu_name"`
	Path       string `json:"path"`
	Icon       string `json:"icon"`
	Roles      string `json:"roles"`
	Layout     int    `json:"layout"`
	ParentId   int    `json:"parent_id"`
	HideInMenu int    `json:"hide_in_menu"`
	Status     *int32 `json:"status"`
}

type BlukelMenuRequest struct {
	Ids string `json:"ids"`
}

type GetMenuTreeRequest struct {
	Roles string `form:"roles"`
}
